/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.cm.liferay.chat.topic.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import it.cm.liferay.chat.topic.service.persistence.TopicUserPK;

import java.io.Serializable;

/**
 * The base model interface for the TopicUser service. Represents a row in the &quot;Conversation_TopicUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.cm.liferay.chat.topic.model.impl.TopicUserModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.cm.liferay.chat.topic.model.impl.TopicUserImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TopicUser
 * @see it.cm.liferay.chat.topic.model.impl.TopicUserImpl
 * @see it.cm.liferay.chat.topic.model.impl.TopicUserModelImpl
 * @generated
 */
@ProviderType
public interface TopicUserModel extends BaseModel<TopicUser>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a topic user model instance should use the {@link TopicUser} interface instead.
	 */

	/**
	 * Returns the primary key of this topic user.
	 *
	 * @return the primary key of this topic user
	 */
	public TopicUserPK getPrimaryKey();

	/**
	 * Sets the primary key of this topic user.
	 *
	 * @param primaryKey the primary key of this topic user
	 */
	public void setPrimaryKey(TopicUserPK primaryKey);

	/**
	 * Returns the topic ID of this topic user.
	 *
	 * @return the topic ID of this topic user
	 */
	public long getTopicId();

	/**
	 * Sets the topic ID of this topic user.
	 *
	 * @param topicId the topic ID of this topic user
	 */
	public void setTopicId(long topicId);

	/**
	 * Returns the user ID of this topic user.
	 *
	 * @return the user ID of this topic user
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this topic user.
	 *
	 * @param userId the user ID of this topic user
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this topic user.
	 *
	 * @return the user uuid of this topic user
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this topic user.
	 *
	 * @param userUuid the user uuid of this topic user
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the group ID of this topic user.
	 *
	 * @return the group ID of this topic user
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this topic user.
	 *
	 * @param groupId the group ID of this topic user
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this topic user.
	 *
	 * @return the company ID of this topic user
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this topic user.
	 *
	 * @param companyId the company ID of this topic user
	 */
	@Override
	public void setCompanyId(long companyId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TopicUser topicUser);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TopicUser> toCacheModel();

	@Override
	public TopicUser toEscapedModel();

	@Override
	public TopicUser toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}