/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.cm.liferay.chat.topic.model.impl;

import aQute.bnd.annotation.ProviderType;

import it.cm.liferay.chat.topic.model.MessageUser;
import it.cm.liferay.chat.topic.service.MessageUserLocalServiceUtil;

/**
 * The extended model base implementation for the MessageUser service. Represents a row in the &quot;Conversation_MessageUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MessageUserImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MessageUserImpl
 * @see MessageUser
 * @generated
 */
@ProviderType
public abstract class MessageUserBaseImpl extends MessageUserModelImpl
	implements MessageUser {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a message user model instance should use the {@link MessageUser} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			MessageUserLocalServiceUtil.addMessageUser(this);
		}
		else {
			MessageUserLocalServiceUtil.updateMessageUser(this);
		}
	}
}